import { readdirSync } from "node:fs";
import path from "node:path";

const ICONS_DIR = path.join(import.meta.dir, "../icons");
const OUTPUT_FILE = path.join(import.meta.dir, "../src/generated/sets.ts");

const entries = readdirSync(ICONS_DIR, { withFileTypes: true });
const sets = entries
  .filter((e) => e.isDirectory())
  .map((e) => e.name)
  .sort();

await Bun.write(
  OUTPUT_FILE,
  `// AUTO-GENERATED by scripts/generate-sets.ts — do not edit\nexport const iconSets = ${JSON.stringify(sets)} as const;\nexport type IconSet = (typeof iconSets)[number];\n`,
);

console.log(`Generated ${OUTPUT_FILE} with ${sets.length} icon sets`);
